"""Add resubmission and feedback form links to Hackathon model

Revision ID: 51b81a5d77ab
Revises: b286706171a1
Create Date: 2025-06-30 00:13:21.508290

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '51b81a5d77ab'
down_revision = 'b286706171a1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hackathon', schema=None) as batch_op:
        batch_op.add_column(sa.Column('resubmission_form_link', sa.String(length=255), nullable=True))
        batch_op.add_column(sa.Column('feedback_form_link', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('hackathon', schema=None) as batch_op:
        batch_op.drop_column('feedback_form_link')
        batch_op.drop_column('resubmission_form_link')

    # ### end Alembic commands ###
