"""Add completion tracking fields to Participant model

Revision ID: b23b0ff135ab
Revises: 51b81a5d77ab
Create Date: 2025-06-30 00:16:07.683291

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b23b0ff135ab'
down_revision = '51b81a5d77ab'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('completion_remarks', sa.Text(), nullable=True))
        batch_op.add_column(sa.Column('uncompletion_email_sent', sa.Boolean(), nullable=True))
        batch_op.add_column(sa.Column('uncompletion_email_sent_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_column('uncompletion_email_sent_at')
        batch_op.drop_column('uncompletion_email_sent')
        batch_op.drop_column('completion_remarks')

    # ### end Alembic commands ###
