"""Add team fields to Participant model

Revision ID: b286706171a1
Revises: 9f613eaa455e
Create Date: 2025-06-25 15:00:42.593533

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b286706171a1'
down_revision = '9f613eaa455e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.add_column(sa.Column('team_name', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('member_position', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('participant', schema=None) as batch_op:
        batch_op.drop_column('member_position')
        batch_op.drop_column('team_name')

    # ### end Alembic commands ###
